// Static manifest of EVERY photo in /public.
// Auto-baked from filesystem — when you drop new photos in, regen via:
//   node -e "..." > src/lib/manifest.ts  (see scripts/bake-manifest.mjs)

export const ALL_REAL: string[] = [
  "/real/real-01.webp",
  "/real/real-02.webp",
  "/real/real-03.webp",
  "/real/real-04.webp",
  "/real/real-05.webp",
  "/real/real-06.webp",
  "/real/real-07.webp",
  "/real/real-08.webp",
  "/real/real-09.webp",
  "/real/real-10.webp",
  "/real/real-11.webp",
  "/real/real-12.webp",
  "/real/real-13.png",
];

export const ALL_DREAM: string[] = [
  "/dream/dream-01-cozy_bohemian_deck_at_sunset.png",
  "/dream/dream-02-cozy_bohemian_dining_room_with_plants.png",
  "/dream/dream-03-cozy_bohemian_rooftop_terrace_at_dusk.png",
  "/dream/dream-04-cozy_bohemian_study_with_warm_glow.png",
  "/dream/dream-05-cozy_boho_bedroom_with_lush_plants.png",
  "/dream/dream-06-cozy_hillside_retreat_at_dusk.png",
  "/dream/dream-07-cozy_plant_filled_kitchen_with_natural_light.png",
  "/dream/dream-08-cozy_vintage_boho_living_room_ambiance.png",
  "/dream/dream-09-elegant_foyer_with_cozy_boho_charm.png",
  "/dream/dream-10-sunlit_bohemian_living_room_oasis.png",
];

export const ALL_INSPO: string[] = [
  "/inspo/01_bohemian_rustic_living_room_retreat.png",
  "/inspo/01_bright_and_cozy_mid_century_living_room.png",
  "/inspo/01_bright_minimalist_scandinavian_living_room.png",
  "/inspo/01_cozy_minimalist_japanese_inspired_interior.png",
  "/inspo/02_bright_mid_century_kitchen_and_dining_space.png",
  "/inspo/02_cozy_cabin_retreat_in_forested_hillside.png",
  "/inspo/02_cozy_evening_deck_with_sunset_glow.png",
  "/inspo/02_minimalist_bedroom_with_natural_accents.png",
  "/inspo/03_cozy_mid_century_modern_living_room.png",
  "/inspo/03_cozy_minimalist_scandinavian_dining_room.png",
  "/inspo/03_cozy_neutral_toned_living_room_retreat.png",
  "/inspo/03_modern_hillside_home_with_zen_garden.png",
  "/inspo/04_cozy_modern_deck_at_twilight.png",
  "/inspo/04_cozy_modern_patio_at_dusk.png",
  "/inspo/04_cozy_rustic_dining_room_ambiance.png",
  "/inspo/04_serene_minimalist_japanese_inspired_foyer.png",
  "/inspo/05_cozy_modern_dining_room_with_fireplace.png",
  "/inspo/05_cozy_scandinavian_living_room_with_fireplace.png",
  "/inspo/05_cozy_sunlit_living_room_with_plants.png",
  "/inspo/05_serene_minimalist_kitchen_and_dining_space.png",
  "/inspo/06_cozy_twilight_deck_with_a_hot_tub.png",
  "/inspo/06_elegant_mediterranean_entry_foyer_with_staircase.png",
  "/inspo/06_elegant_mediterranean_foyer_with_arches.png",
  "/inspo/06_serene_minimalist_living_room_design.png",
  "/inspo/07_golden_hour_on_a_cozy_terrace.png",
  "/inspo/07_minimalist_mediterranean_foyer_with_staircase.png",
  "/inspo/07_modern_hillside_home_at_golden_hour.png",
  "/inspo/07_tranquil_evening_patio_with_bonsai_trees.png",
  "/inspo/08_modern_farmhouse_kitchen_with_cozy_dining_nook.png",
  "/inspo/08_modern_outdoor_deck_at_dusk.png",
  "/inspo/08_modern_scandinavian_kitchen_with_island_setup.png",
  "/inspo/08_tranquil_japanese_inspired_outdoor_retreat.png",
  "/inspo/09_modern_rustic_living_space_with_fireplace.png",
  "/inspo/09_scandinavian_style_bedroom_with_natural_light.png",
  "/inspo/09_serene_coastal_farmhouse_bedroom_interior.png",
  "/inspo/09_zen_inspired_minimalist_living_room.png",
  "/inspo/10_serene_minimalist_modern_bedroom_design.png",
  "/inspo/10_twilight_retreat_in_the_forest.png",
  "/inspo/inspo-01-bohemian_cozy_living_room_with_plants.png",
  "/inspo/inspo-02-bright_and_modern_kitchen_with_wood_accents.png",
  "/inspo/inspo-03-bright_minimalist_dining_room_with_greenery.png",
  "/inspo/inspo-04-contemporary_hillside_home_with_lush_greenery.png",
  "/inspo/inspo-05-cozy_backyard_patio_with_string_lights.png",
  "/inspo/inspo-06-cozy_bohemian_bedroom_with_warm_sunlight.png",
  "/inspo/inspo-07-cozy_bohemian_dining_room_ambiance.png",
  "/inspo/inspo-08-cozy_bohemian_hallway_with_plants.png",
  "/inspo/inspo-09-cozy_boho_dining_room_at_dusk.png",
  "/inspo/inspo-10-cozy_boho_evening_deck_retreat.png",
  "/inspo/inspo-11-cozy_boho_living_room_with_fireplace.png",
  "/inspo/inspo-12-cozy_boho_rooftop_terrace_at_dusk.png",
  "/inspo/inspo-13-cozy_cottage_inspired_bedroom_retreat.png",
  "/inspo/inspo-14-cozy_dusk_deck_with_hot_tub.png",
  "/inspo/inspo-15-cozy_elegant_living_room_ambiance.png",
  "/inspo/inspo-16-cozy_evening_patio_retreat.png",
  "/inspo/inspo-17-cozy_evening_patio_with_string_lights.png",
  "/inspo/inspo-18-cozy_farmhouse_dining_in_sunlight.png",
  "/inspo/inspo-19-cozy_hillside_cabin_at_twilight.png",
  "/inspo/inspo-20-cozy_hillside_cabin_with_warm_lights.png",
  "/inspo/inspo-21-cozy_mediterranean_style_terrace_at_golden_hour.png",
  "/inspo/inspo-22-cozy_mid_century_modern_dining_room.png",
  "/inspo/inspo-23-cozy_modern_dining_room_with_greenery.png",
  "/inspo/inspo-24-cozy_modern_kitchen_with_natural_accents.png",
  "/inspo/inspo-25-cozy_modern_minimalist_living_room.png",
  "/inspo/inspo-26-cozy_patio_at_dusk_with_string_lights.png",
  "/inspo/inspo-27-cozy_patio_with_warm_evening_glow.png",
  "/inspo/inspo-28-cozy_rustic_dining_room_ambiance.png",
  "/inspo/inspo-29-cozy_rustic_dining_room_with_zen_accents.png",
  "/inspo/inspo-30-cozy_rustic_living_room_with_fireplace.png",
  "/inspo/inspo-31-cozy_scandinavian_inspired_living_room_design.png",
  "/inspo/inspo-32-cozy_scandinavian_living_room_with_fire.png",
  "/inspo/inspo-33-cozy_sunlit_kitchen_with_earthy_charm.png",
  "/inspo/inspo-34-cozy_twilight_deck_with_ambient_lighting.png",
  "/inspo/inspo-35-cozy_twilight_terrace_with_greenery_and_firepit.png",
  "/inspo/inspo-36-cozy_vintage_modern_living_room_interior.png",
  "/inspo/inspo-37-cozy_woodland_deck_at_golden_hour.png",
  "/inspo/inspo-38-elegant_mediterranean_foyer_with_grand_staircase.png",
  "/inspo/inspo-40-minimalist_japanese_scandi_foyer_with_staircase.png",
  "/inspo/inspo-41-minimalist_scandinavian_kitchen_with_natural_light.png",
  "/inspo/inspo-42-modern_hillside_home_with_expansive_glass_facade.png",
  "/inspo/inspo-43-modern_hillside_home_with_terrace.png",
  "/inspo/inspo-44-modern_hillside_home_with_warm_lighting.png",
  "/inspo/inspo-45-modern_minimalist_bedroom_with_natural_light.png",
  "/inspo/inspo-46-modern_scandinavian_dining_with_fireplace_warmth.png",
  "/inspo/inspo-47-modern_scandinavian_entry_foyer_with_greenery.png",
  "/inspo/inspo-48-serene_evening_terrace_with_lush_greenery.png",
  "/inspo/inspo-49-serene_hillside_retreat_with_modern_design.png",
  "/inspo/inspo-50-serene_japanese_scandinavian_bedroom_retreat.png",
  "/inspo/inspo-51-serene_minimalist_bedroom_with_natural_light.png",
  "/inspo/inspo-52-serene_minimalist_dining_space.png",
  "/inspo/inspo-53-serene_minimalist_living_room_interior.png",
  "/inspo/inspo-54-serene_modern_outdoor_terrace_at_dusk.png",
  "/inspo/inspo-55-serene_zen_inspired_outdoor_terrace_at_dusk.png",
  "/inspo/inspo-56-sunlit_farmhouse_entry_with_cozy_decor.png",
  "/inspo/inspo-57-twilight_elegance_in_modern_hillside_home.png",
  "/inspo/inspo-58-twilight_view_of_a_modern_woodland_home.png",
  "/inspo/inspo-59-warm_and_serene_modern_living_room.png",
  "/inspo/inspo-60-warm_minimalist_kitchen_with_dining_nook.png",
  "/inspo/original_ref_01__073f8cbad919568b58dd86dbea3ce75e-cc_ft_576.webp",
  "/inspo/original_ref_02__3f302b88be749146d209ef806769943e-cc_ft_1152.webp",
  "/inspo/original_ref_03__47a28562192dba7720c8cfa2e01de89d-cc_ft_576.webp",
  "/inspo/original_ref_04__5fd591621795ed42cbe69ecdc8d74366-cc_ft_576.webp",
  "/inspo/original_ref_05__67f467e38667c9f1058546b5fb188ddd-cc_ft_1152.webp",
  "/inspo/original_ref_06__687797aef96a15f3dac58bcb49002656-cc_ft_768.webp",
  "/inspo/original_ref_07__769eb6b37ccada92b85ecd466b57b565-cc_ft_1152.webp",
  "/inspo/original_ref_08__8727e9a78d1994094848f15b37875d58-cc_ft_1152.webp",
  "/inspo/original_ref_09__a506673ec80f47302e4aece3cdac960d-cc_ft_1152.webp",
  "/inspo/original_ref_10__b5147b1dd200ce7156268994091e0537-cc_ft_1536.webp",
  "/inspo/original_ref_11__bce3cb43719cd2efeff5a3e26a050ca1-cc_ft_576.webp",
  "/inspo/original_ref_12__e04588e1ad7ec01f3ca8a1737705b0ae-cc_ft_1536.webp",
  "/inspo/style_ref_01__Screenshot_2026-06-01_at_10.22.43_PM2.png",
  "/inspo/style_ref_02__Screenshot_2026-06-01_at_10.22.55_PM2.png",
  "/inspo/style_ref_03__Screenshot_2026-06-01_at_10.23.17_PM2.png",
  "/inspo/style_ref_04__Screenshot_2026-06-01_at_10.23.23_PM2.png",
  "/inspo/style_ref_05__Screenshot_2026-06-01_at_10.23.31_PM2.png",
  "/inspo/style_ref_06__Screenshot_2026-06-01_at_9.51.44_PM.png",
  "/inspo/style_ref_07__Screenshot_2026-06-01_at_9.54.04_PM.png",
];

// Filter helpers — match by keyword in filename
export function inspoMatching(keywords: string[]): string[] {
  return ALL_INSPO.filter((p) =>
    keywords.some((k) => p.toLowerCase().includes(k.toLowerCase()))
  );
}

// Combined photo set (everything)
export const EVERY_PHOTO: string[] = [
  ...ALL_REAL,
  ...ALL_DREAM,
  ...ALL_INSPO,
];
